### ISSUE TITLE
Make a new program

### ISSUE THREAD

**Issue by tinyCodersDen** [kethan1/Coding-Ideas#1]
Try making a universal translator that takes speech input, translates it to any other language, and then the program speaks to you in another language. One more suggestion is what I call the "Hangry Birds" Project. Make a TensorFlow classifier that detects any pigeons on the raspberry pi camera, and then plays a sound to scare the extra hungry pigeons away, a useful application for birdhouse management.

**Comment by kethan1** [comment]
Cool project ideas! Will edit the readme soon

**Comment by tinyCodersDen** [comment]
Sure, I decided to add here because you added to my py-data-structure module. But sure.
